### ISSUE TITLE
It keeps returning my IP Address can you help?

### ISSUE THREAD

**Issue by op0x59** [devRyle/Basic-Dumper#1]
help

**Comment by op0x59** [comment]
It's also returning my actual address, full name
Phone Number
Parents name

**Comment by devRyle** [comment]
![G_cLzk3oSCeIA338fmjXRg](https://user-images.githubusercontent.com/64764764/92073027-a222ae00-ed80-11ea-9aca-e1a8e999e4c6.png)

**Comment by op0x59** [comment]
DUDDEEE WTF FFFFF SEE WHY IS EVERYTHING RESPONDING WITH MY INFO!@!!H189UIYIH!ou
